create TABLE IF NOT EXISTS users
(
    id            int generated by default as identity primary key,
    email	      varchar(100) NOT NULL,
    login         varchar(100) NOT NULL,
    name          varchar(100),
    birthday      timestamp
);

CREATE TABLE IF NOT EXISTS friends(
	id 			  int GENERATED BY DEFAULT  AS IDENTITY PRIMARY KEY,
	user_id 	  int REFERENCES users (id),
	friend_id 	  int REFERENCES users (id),
	status   	  boolean DEFAULT FALSE,
	UNIQUE(user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS mpa(
 mpa_id    		  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 mpa_name 			  varchar(10) NOT NULL,
 UNIQUE(mpa_name)
);

CREATE TABLE IF NOT EXISTS genre(
genre_id 		  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
genre_name  			  varchar(50) NOT NULL,
UNIQUE(genre_name)
);

create TABLE IF NOT EXISTS films
(
    id            int generated by default as identity primary key,
    name	      varchar(100) NOT NULL,
    description   varchar(200),
    release_date  timestamp,
    duration      int,
    mpa_id 		  int REFERENCES mpa(mpa_id),
    genre_id	  int REFERENCES genre(genre_id)
);

CREATE TABLE IF NOT EXISTS film_likes(
	id 			  int generated by default as identity primary key,
	film_id 	  int REFERENCES films(id),
	user_id 	  int REFERENCES users(id)
);

